scalar BigInt

type YieldDex_FeeRecipient {
  id: ID!
  recipient: String!
}

type YieldDex_L1ReportHash {
  id: ID!
  hash: String!
}

type YieldDex_StrategyRegistered {
  id: ID!
  l1Strategy: String!
  l2Strategy: String!
  token: String!
  underlying: String!
  performanceFees: String!
  tvlLimit: String!
}

type YieldDex_PerformanceFeeUpdated {
  id: ID!
  l1Strategy: String!
  l2Strategy: String!
  newPerfomanceFees: String!
}

type YieldDex_WithdrawalEpochUpdated {
  id: ID!
  l1Strategy: String!
  l2Strategy: String!
  newWithdrawalEpochDelay: String!
}

type YieldDex_DustLimitUpdated {
  id: ID!
  l1Strategy: String!
  newDustLimit: String!
}

type YieldDex_Deposit {
  id: ID!
  l1Strategy: String!
  l2Strategy: String!
  caller: String!
  receiver: String!
  assets: String!
  shares: String!
  referal: String!
  timestamp: Int!
}

type YieldDex_RequestWithdrawal {
  id: ID!
  l1Strategy: String!
  l2Strategy: String!
  caller: String!
  assets: String!
  shares: String!
  withdrawalId: String!
  epoch: Int!
  timestamp: Int!
}

type YieldDex_ClaimWithdrawal {
  id: ID!
  l1Strategy: String!
  l2Strategy: String!
  caller: String!
  claimId: String!
  underlyingAmount: String!
  timestamp: Int!
}

type YieldDex_BridgeInteractionInfo {
  id: ID!
  l1Bridge: String!
  amount: String!
  timestamp: Int!
}

type YieldDex_TvlLimitUpdated {
  id: ID!
  l1Strategy: String!
  l2Strategy: String!
  newTvlLimit: String!
}

type YieldDex_StrategyL2Report {
  id: ID!
  l1Strategy: String!
  actionId: String!
  amount: String!
  newSharePrice: String!
  timestamp: Int!
}

type YieldDex_NewL2Report {
  id: ID!
  hash: String!
  timestamp: Int!
  blockNumber: Int!
  newEpoch: String!
  newBridgeDeposit: [YieldDex_BridgeInteractionInfo!]
  newL2Report: [YieldDex_StrategyL2Report!]
  newBridgeWithdraw: [YieldDex_BridgeInteractionInfo!]
}

type Liquity_Batch {
  id: ID!
  hash: String!
  address: String!
  block: Int!
  nonce: Int!
  eth: String!
  lusd: String!
  timestamp: Int!
}

type YieldDex_TM_Transfer {
  id: ID!
  contractAddress: String!
  from: String!
  to: String!
  value: String!
  timestamp: Int!
}

type YieldDex_TM_balanceOf {
  id: ID!
  balance: String!
}

type YieldDex_TM_holders {
  id: ID!
  holders: Int!
}