name: build-deploy

on:
  push:
    branches:
      - main

env:
  working-directory: .
  DOCKER_IMAGE: spaceshard/nimbora-yielddex-indexer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn install
      - name: Docker Build image
        run: docker build . -t ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker push image
        run: docker tag ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }} ${{ env.DOCKER_IMAGE }}:latest
